### ISSUE TITLE
Branches prioritised over main line

### ISSUE THREAD

**Issue by adelino-santos** [Marken-Foo/tsumemi#3]
![image](https://user-images.githubusercontent.com/7833009/105782066-ab006000-5f6b-11eb-80b3-8eabc625c07a.png)
Expected behaviour: 
２四桂打

Thanks for the great work as always!

Example kif:
---------
# ---- 柿木将棋形式棋譜ファイル
# ----   generated by IS-SHOGI
手合割：詰将棋　
後手の持駒：飛二　角二　金三　銀四　桂三　香四　歩十七　
  ９ ８ ７ ６ ５ ４ ３ ２ １
+---------------------------+
| ・ ・ ・ ・ ・ ・ ・ ・v玉|一
| ・ ・ ・ ・ ・ ・ ・ 歩 ・|二
| ・ ・ ・ ・ ・ ・ ・ 金 ・|三
| ・ ・ ・ ・ ・ ・ ・ ・ ・|四
| ・ ・ ・ ・ ・ ・ ・ ・ ・|五
| ・ ・ ・ ・ ・ ・ ・ ・ ・|六
| ・ ・ ・ ・ ・ ・ ・ ・ ・|七
| ・ ・ ・ ・ ・ ・ ・ ・ ・|八
| ・ ・ ・ ・ ・ ・ ・ ・ ・|九
+---------------------------+
先手の持駒：桂　
先手番
先手：
後手：
手数----指手---------消費時間--
*第１問
   1 ２四桂打     ( 0:00/00:00:00) ( 0:00/00:00:00)
*正解図
変化：1手
   1 １三桂打     ( 0:00/00:00:00) ( 0:00/00:00:00)
   2 １二角打     ( 0:00/00:00:00) ( 0:00/00:00:00)
   3 ２一歩成(22) ( 0:00/00:00:00) ( 0:00/00:00:00)
   4 同　角(12)   ( 0:00/00:00:00) ( 0:00/00:00:00)
   5 同　桂成(13) ( 0:00/00:00:00) ( 0:00/00:00:00)
   6 同　玉(11)   ( 0:00/00:00:00) ( 0:00/00:00:00)
   7 ４三角打     ( 0:00/00:00:00) ( 0:00/00:00:00)
   8 １一玉(21)   ( 0:00/00:00:00) ( 0:00/00:00:00)
   9 ３二角成(43) ( 0:00/00:00:00) ( 0:00/00:00:00)
  10 ２一歩打     ( 0:00/00:00:00) ( 0:00/00:00:00)
*参考図
#--separator--

**Comment by Marken-Foo** [comment]
Thanks for the feedback! There were two issues here: comment lines beginning with `#` or `*` caused the next line to be skipped, and the branch moves were not being ignored.
The kif parser will be rewritten in the future, but for now a quick bugfix. https://github.com/Marken-Foo/kif-browser/commit/c1ec70c21ab98350e47bb1fbfca25c22ab31227c
